### ISSUE TITLE
Anuj bhai polymorphism ke MCQs ka karo kuchh

### ISSUE THREAD

**Issue by BilakshanP** [Anuj-er/Testpad-Solutions#1]

**Comment by BilakshanP** [comment]
<3

**Comment by Anuj-er** [comment]
Theek h bhai i will try my best !

**Comment by BilakshanP** [comment]
> Theek h bhai i will try my best !

:), mere se hue toh main pull request daal dunga

**Comment by Anuj-er** [comment]
Added Polymorphism-11
https://github.com/Anuj-er/Testpad-Solutions/blob/main/22CS006-Object%20Oriented%20Programming%20in%20C%20-%203rdSem/5.%20Run%20time%20Polymorphism/13.%20Polymorphism%20-%2011/Answer.txt
and Polymorphism-12
https://github.com/Anuj-er/Testpad-Solutions/blob/main/22CS006-Object%20Oriented%20Programming%20in%20C%20-%203rdSem/5.%20Run%20time%20Polymorphism/14.%20Polymorphism%20-%2012/Answer.txt

**Comment by Anuj-er** [comment]
Added Polymorphism-9
https://github.com/Anuj-er/Testpad-Solutions/blob/main/22CS006-Object%20Oriented%20Programming%20in%20C%20-%203rdSem/5.%20Run%20time%20Polymorphism/11.%20Polymorphism%20-%209/Answer.txt

**Comment by Anuj-er** [comment]
To close this issue, here’s a final comment you can post
